// const productos = [{
//     id:1,
//     nombre: "Bandolera Milan",
//     precio: 2500,
//     stock: 10,
//     descripcion:"Bandolera con correa ajustable, forrada por dentro",
//     img:"../public/img/Bandolera.png"},
//     {
//     id:2,
//     nombre: "Mochila california",
//     precio: 5000,
//     stock: 10,
//     descripcion:"Mochila de cuero, color negro, con doble cierre",
//     img:"../public/img/mochila-cali.jpg"},
//     {
//     id:3,
//     nombre: "Cinto Melania",
//     precio: 1999,
//     stock: 10,
//     descripcion:"Cinto de cuero, color negro, con detalles metalicos",
//     img:"../public/img/cinto.png"},
//     {
//     id:4,
//     nombre: "Tobillera",
//     precio: 1500,
//     stock: 10,
//     descripcion:"Tobillera beige, para disfrutar este verano",
//     img:"../public/img/tobillera.jpg"},
//     {
//     id:5,
//     nombre: "Bolso Melania",
//     precio: 4500,
//     stock: 10,
//     descripcion:"Bolso de cuero negro, estilo cocodrilo",
//     img:"../public/img/bolso-cuero.jpg"},
//     {
//     id:6,
//     nombre: "Bolso California",
//     precio: 4900,
//     stock: 10,
//     descripcion:"Bolso negro mate, con detalles metalicos",
//     img:"../public/img/bolso.jpg"},
//     {
//     id:7,
//     nombre: "Pañuelo",
//     precio: 1000,
//     stock: 10,
//     descripcion:"Pañuelo para disfrutar en invierno",
//     img:"../public/img/pañuelo-negro.jpg"},
//     {
//     id:8,
//     nombre: "Pañuelo y Cadenita",
//     precio: 1900,
//     stock: 10,
//     descripcion:"Combo pañuelo mas cadenita",
//     img:"../public/img/pañuelo-azul.jpg"},
//     {
//     id:9,
//     nombre: "Gorrito Melania",
//     precio: 1000,
//     stock: 10,
//     descripcion:"Gorrito azul para este verano",
//     img:"../public/img/gorrito-azul.png",}
// ];